name: Run Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install -i

      - name: Run local server
        run: npm run tern-on-api & sleep 10

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run API tests
        run: newman run store.postman_collection.json --environment testEnv.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html

      - name: Sleep
        run: sleep 10

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: RunReports
          path: testResults

  deploy-report:
    needs: postman-tests
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: RunReports
          path: testResults

      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: report
          folder: ./testResults
